### ISSUE TITLE
[error] problems with KoFamKOALA

### ISSUE THREAD

**Issue by ShailNair** [Matteopaluh/KEMET#5] opened 2022-04-21 08:45 UTC
Hi, 

Thanks for the kemet package. The package and the article looks awesome.
I installed kemet following the instructions and when i run it, i get the following error: 

`python kemet.py genomes/mcs.fasta -a kofamkoala --hmm_mode kos

Traceback (most recent call last):
  File "kemet.py", line 2514, in <module>
    if LOGflag:
NameError: name 'LOGflag' is not defined`

**Comment by Matteopaluh** [comment] 2022-04-21 09:12
Thank you for the kind words Shail,
this one was definitely a very dull error on my side, my bad.

With the recent commit it should be fixed, as I wrote the code as if the logging option was always chosen.

I'll suggest to clone again the repository and moving your files in the new one, to try again.
Feel free to reopen if the problem is not properly fixed.

Best regards,
Matteo

**Comment by ShailNair** [comment] 2022-04-22 03:05
i used --log option but now throws a a new error

`python kemet.py genomes/mcs.fasta -a kofamkoala --hmm_mode kos --log

Traceback (most recent call last):
  File "kemet.py", line 2531, in <module>
    ktest, KOs = kofamXktest(file, file.rsplit(".",1)[0]+".ktest", KAnnotation_directory, ktests_directory)
  File "kemet.py", line 155, in kofamXktest
    fastaslice = spacer.index(" ",1)+1

ValueError: substring not found
`

The same error occurs with the updated repository (without --log option)

i used kofamkoala ko output as kegg annotations. e.g.

g1.t1
g2.t1	K01689
g3.t1
g4.t1	K22696

**Comment by Matteopaluh** [comment] 2022-04-22 07:19
Hi again,
the log issue is solved then.

Regarding this other problem with kofam, I believe it is due to a wrong annotation type selection.

In the KEMET toy folder, [here](https://github.com/Matteopaluh/KEMET/tree/main/toy), there are indications on the expected format of annotation files, how those should be structured, based on the various softwares output.

From the example you added, KoFamKOALA with KO output results in a "kaas-like" annotation as the ["bin1_ko.txt"](https://github.com/Matteopaluh/KEMET/blob/main/toy/bin1_ko.txt) file from toy folder (i.e. a tab separated file, with two fields - 1st for gene name/locus, 2nd for KEGG KO).

Therefore, I'd suggest to clean the output folders (the ones with "reports") use a different command than the one you used, as KEMET won't find any KoFamKOALA formatted files:

`
python kemet.py genomes/mcs.fasta -a kaas --hmm_mode kos --log
`

I'll also highlight the formatting rules fom other potential users! Thanks.
This should resolve the issue.

**Comment by ShailNair** [comment] 2022-04-22 08:24
thanks. that worked.

**Closed as completed** 2022-04-22 08:47 UTC
